name: '@prismoid - Release'

on:
  workflow_call:
    inputs:
      package-directory:
        required: true
        type: string
    secrets:
      github-token:
        required: true
      npm-token:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.package-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          NPM_TOKEN: ${{ secrets.npm-token }}
