name: '@prismoid - Release'

on:
  workflow_run:
    workflows:
      - '@prismoid - Test'
    branches:
      - 'main'
    types:
      - completed

jobs:
  release-core:
    name: Release @prismoid/core
    uses: loopholelabs/prismoid/.github/workflows/release-base.yml@main
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    concurrency:
      group: ${{ github.head_ref }}
    with:
      package-directory: packages/core
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}

  release-grammars:
    name: Release @prismoid/grammars
    uses: loopholelabs/prismoid/.github/workflows/release-base.yml@main
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    concurrency:
      group: ${{ github.head_ref }}
    with:
      package-directory: packages/grammars
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}

  release-react:
    name: Release @prismoid/react
    uses: loopholelabs/prismoid/.github/workflows/release-base.yml@main
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    concurrency:
      group: ${{ github.head_ref }}
    with:
      package-directory: packages/react
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}
