name: '@prismoid - Test'

on: [push]

jobs:
  test-core:
    name: Test @prismoid/core
    uses: loopholelabs/prismoid/.github/workflows/test-base.yml@main
    with:
      build-command: yarn build:grammars && yarn build:core
      test-command: yarn test:core

  test-grammars:
    name: Test @prismoid/grammars
    uses: loopholelabs/prismoid/.github/workflows/test-base.yml@main
    with:
      build-command: yarn build:grammars
      test-command: yarn test:grammars

  test-react:
    name: Test @prismoid/react
    uses: loopholelabs/prismoid/.github/workflows/test-base.yml@main
    with:
      build-command: yarn build:react
      test-command: yarn test:react
